### PR TITLE
Adds Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by marcosvidolin**

### CODE REVIEW

**Comment by czytelny** [comment]
awesome, thanks! I'll release new beta soon with translations

**Comment by czytelny** [comment]
@marcosvidolin sorry for this lame question but which flag should I use to represent this language ? I want to add a language picker with flags from: http://flag-icon-css.lip.is

**Comment by marcosvidolin** [comment]
Hi @czytelny 
Use Brazil flag (Alpha-2 code = BR)

**Comment by czytelny** [comment]
Hi, I added bunch of new labels - do you have time to translate it ? If no I'll use google translate, just let me know. By the way: I'm using this app for managing translations, it's pretty good: https://github.com/gilmarsquinelato/i18n-manager

**Comment by marcosvidolin** [comment]
Hi, 
Nice! You can count on me to translate.

;)

**Pull request merged**
